# Generated by Django 4.0.2 on 2022-03-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
