# Generated by Django 4.0.2 on 2022-03-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adress',
            new_name='address',
        ),
    ]
