# Generated by Django 4.0.6 on 2022-07-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0007_location_room_hotel_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
