# Generated by Django 4.0.6 on 2022-07-16 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0011_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.amenities'),
        ),
    ]
