# Generated by Django 4.0.6 on 2022-07-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0013_remove_hotel_amenities_amenities_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='hotel',
        ),
        migrations.AddField(
            model_name='amenities',
            name='icon',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(to='hotelbooking.amenities'),
        ),
    ]
