# Generated by Django 4.0.6 on 2022-07-25 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0016_rename_amount_booking_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.hotel'),
        ),
    ]
