# Generated by Django 4.0.6 on 2022-07-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0017_booking_hotel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel_name',
        ),
    ]
