# Generated by Django 4.0.6 on 2022-07-25 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0018_remove_booking_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.hotel'),
        ),
    ]
