# Generated by Django 4.0.6 on 2022-07-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0020_alter_booking_check_in_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='hotel_name',
            new_name='hotel_id',
        ),
    ]
