# Generated by Django 4.0.6 on 2022-07-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0023_alter_booking_from_date_alter_booking_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_date',
            field=models.DateField(),
        ),
    ]
