# Generated by Django 4.0.6 on 2022-07-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0024_alter_booking_from_date_alter_booking_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
