# Generated by Django 4.0.6 on 2022-08-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0027_alter_manager_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='picture',
        ),
    ]
